name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    run-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        run: |
          pip install uv -U

      - name: Create virtual environment
        run: |
          uv venv

      - name: 
        run: Activate virtual environment
          source .venv/bin/activate
          uv sync --active

      - name: Run test with coverage
        run: |
          coverage run -m pytest
          coverage report
